// src/app/app.component.ts
import { Component } from '@angular/core';
import { SliderProvenance } from 'provenance-widgets';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'provenance-demo';

  // Slider/Range slider attributes - START
  value: number = 0;
  highValue: number = 250;
  options = {
    floor: 0, ceil: 250, showTicks: true, tickStep: 25
  }

  // Implicit 2-way binding for provenance
  sliderProvenance?: SliderProvenance = undefined
  
  // Explicit 2-way binding for provenance
  rangeSliderProvenance?: SliderProvenance = undefined
  handleRangeSliderProvenanceChange(event: SliderProvenance) {
    this.rangeSliderProvenance = event;
  }
  // Slider/Range slider attributes - END
  
  // Selection-type widgets attributes - START
  cities = [
    {
      name: 'New York',
      code: 'New York',
      inputId: 'NY'
    },
    {
      name: 'Rome',
      code: 'Rome',
      inputId: 'RM'
    },
    {
      name: 'London',
      code: 'London',
      inputId: 'LDN'
    },
    {
      name: 'Istanbul',
      code: 'Istanbul',
      inputId: 'IST'
    },
    {
      name: 'Paris',
      code: 'Paris',
      inputId: 'PRS'
    }
  ];

  // Implicit 2-way binding for provenance
  checkbox_selected = this.cities.slice(0, 2).map(c => c.code);
  radio_selected = this.cities[0].code;
  dropdown_selected?: string = undefined

  // Explicit 2-way binding for provenance
  multiselect_selected = this.cities.slice(0, 2);
  handleMultiselectChange(event: typeof this.multiselect_selected) {
    this.multiselect_selected = event;
  }

  // Selection-type widgets attributes - END
}

<div style="width: 50%;">
  <label for="s-interaction">Slider</label>
  <provenance-slider
    id="s-interaction"
    [value]="value"
    [options]="options"
    [attr.data-label]="'Interaction slider'"
    [(provenance)]="sliderProvenance"
  >
  </provenance-slider>
  <hr/>
  <label for="rs-interaction">Range Slider</label>  
  <provenance-slider
    id="rs-interaction"
    [value]="value"
    [highValue]="highValue"
    [options]="options"
    [attr.data-label]="'Interaction slider'"
    [provenance]="rangeSliderProvenance"
    (provenanceChange)="handleRangeSliderProvenanceChange($event)"
  >
  </provenance-slider>
  <hr/>
  <label for="d-interaction">Dropdown</label>
  <provenance-dropdown
    id="d-interaction"
    [options]="cities"
    optionLabel="name"
    dataKey="code"
    placeholder="Select a City"
    [(selected)]="dropdown_selected"
  >
  </provenance-dropdown>
  <hr/>
  <label for="m-interaction">Multiselect</label>
  <provenance-multiselect
    id="m-interaction"
    [options]="cities"
    optionLabel="name"
    dataKey="code"
    placeholder="Select a City"
    [selected]="multiselect_selected"
    (selectedChange)="handleMultiselectChange($event)"
  >
  </provenance-multiselect>
  <hr/>
  <label for="i-interaction">Inputtext</label>
  <provenance-inputtext
    id="i-interaction"
    [value]="title"
    [attr.data-label]="'Interaction inputtext'"
  >
  </provenance-inputtext>
  <hr/>
  <label for="c-interaction">Checkbox</label>
  <provenance-checkbox
    id="c-interaction"
    [data]="cities"
    label="name" 
    value="code" 
    name="undefined"
    [(selected)]="checkbox_selected"
  >
  </provenance-checkbox>
  <hr/>
  <label for="r-interaction">Radiobutton</label>
  <provenance-radiobutton
    id="r-interaction"
    [data]="cities"
    label="name" 
    value="code" 
    name="r-interaction"
    [(selected)]="radio_selected"
  >
  </provenance-radiobutton>
</div>

// src/App.jsx
import { useState } from "react";
import {
  CheckboxGroup,
  InputText,
  MultiSelectDropdown,
  ProvenanceButton,
  RadioGroup,
  Rangeslider,
  Singleslider,
  SingleSelectDropdown,
} from "provenance-widgets";

const cities = [
  { name: "New York", code: "New York" },
  { name: "Rome", code: "Rome" },
  { name: "London", code: "London" },
  { name: "Istanbul", code: "Istanbul" },
  { name: "Paris", code: "Paris" },
];

const sliderOptions = {
  floor: 0,
  ceil: 250,
  step: 1,
  showTicks: true,
  tickStep: 25,
};

function Example({ id, title, children }) {
  const headingId = `${id}-heading`;

  return (
    <section className="example" aria-labelledby={headingId}>
      <h2 id={headingId}>{title}</h2>
      <div className="example__body">
        <div className="example__footprint">
          <ProvenanceButton target={id} />
        </div>
        <div className="example__control">{children}</div>
      </div>
    </section>
  );
}

export default function App() {
  const [sliderValue, setSliderValue] = useState(0);
  const [rangeValue, setRangeValue] = useState([0, 250]);
  const [dropdownValue, setDropdownValue] = useState(null);
  const [multiSelectValue, setMultiSelectValue] = useState(
    cities.slice(0, 2),
  );
  const [inputValue, setInputValue] = useState("provenance-demo");
  const [checkboxValue, setCheckboxValue] = useState([
    "New York",
    "Rome",
  ]);
  const [radioValue, setRadioValue] = useState("New York");

  const logProvenance = (id, provenance, meta) => {
    console.info(`[${id}] provenanceChange`, provenance, meta);
  };

  return (
    <main>
      <div className="examples">
        <Example id="starter-slider" title="Slider">
          <Singleslider
            id="starter-slider"
            dataLabel="Interaction slider"
            value={sliderValue}
            options={sliderOptions}
            visualize
            onChange={setSliderValue}
            onProvenanceChange={(provenance, meta) =>
              logProvenance("starter-slider", provenance, meta)
            }
          />
        </Example>

        <Example id="starter-range-slider" title="Range Slider">
          <Rangeslider
            id="starter-range-slider"
            dataLabel="Interaction range slider"
            value={rangeValue}
            options={sliderOptions}
            visualize
            onChange={setRangeValue}
            onProvenanceChange={(provenance, meta) =>
              logProvenance("starter-range-slider", provenance, meta)
            }
          />
        </Example>

        <Example id="starter-dropdown" title="Dropdown">
          <SingleSelectDropdown
            id="starter-dropdown"
            dataLabel="City"
            options={cities}
            optionLabel="name"
            optionValue="code"
            dataKey="code"
            placeholder="Select a city"
            selected={dropdownValue}
            visualize
            onSelectedChange={setDropdownValue}
            onProvenanceChange={(provenance, meta) =>
              logProvenance("starter-dropdown", provenance, meta)
            }
          />
        </Example>

        <Example id="starter-multiselect" title="Multiselect">
          <MultiSelectDropdown
            id="starter-multiselect"
            dataLabel="Cities"
            options={cities}
            optionLabel="name"
            optionValue="code"
            dataKey="code"
            placeholder="Select cities"
            selected={multiSelectValue}
            visualize
            onSelectedChange={setMultiSelectValue}
            onProvenanceChange={(provenance, meta) =>
              logProvenance("starter-multiselect", provenance, meta)
            }
          />
        </Example>

        <Example id="starter-inputtext" title="Input Text">
          <InputText
            id="starter-inputtext"
            dataLabel="Search text"
            value={inputValue}
            placeholder="Search"
            visualize
            onValueChange={setInputValue}
            onProvenanceChange={(provenance, meta) =>
              logProvenance("starter-inputtext", provenance, meta)
            }
          />
        </Example>

        <Example id="starter-checkbox" title="Checkbox">
          <CheckboxGroup
            id="starter-checkbox"
            name="starter-checkbox"
            dataLabel="Cities"
            data={cities}
            optionLabel="name"
            optionValue="code"
            dataKey="code"
            selected={checkboxValue}
            visualize
            onSelectedChange={setCheckboxValue}
            onProvenanceChange={(provenance, meta) =>
              logProvenance("starter-checkbox", provenance, meta)
            }
          />
        </Example>

        <Example id="starter-radiobutton" title="Radio Button">
          <RadioGroup
            id="starter-radiobutton"
            name="starter-radiobutton"
            dataLabel="City"
            data={cities}
            optionLabel="name"
            optionValue="code"
            dataKey="code"
            selected={radioValue}
            visualize
            onSelectedChange={setRadioValue}
            onProvenanceChange={(provenance, meta) =>
              logProvenance("starter-radiobutton", provenance, meta)
            }
          />
        </Example>
      </div>
    </main>
  );
}
